{
 "title": "Golden Signals",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_TEMPO", "query": "tempo" },
   { "name": "DS_LOKI", "query": "loki" },
   {
    "name": "service_name",
    "label": "Apps",
    "query": "AuthService, SessionManager, TokenGenerator, TokenVerify"
   },
   {
    "name": "service_namespace",
    "label": "Service",
    "query": "Accounts, Cards, Investments, Login, Payments, Transactions, Transfers"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "Development, Staging, Production"
   },
   { "name": "quant", "label": "Quantile", "query": "0.50, 0.90, 0.95, 0.97, 0.99" },
   {
    "name": "component",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Top Left Branding -->\n<table style=\"border: none;width:100%;\">\n  <tr>\n    <!-- Logos --> \n    <td style=\"border: none;padding-top:0px\"><div style='width: 140px;'><img src='https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/b6d9ced907fbdc4d6aecf6c5ef3f1c77750f4550/logos/richbank-logo-green.svg'height=\"50\"></td>\n    <!-- Dynamic Horizontal Line -->\n    <td style=\"border: none;padding-top:0px;width:100%;\"><hr></td></td>\n  </tr>\n</table>\n<!-- Everything Else -->\n<table style=\"border: none;width: 100%;\">\n  <tr>\n    <!-- Dashboard Title / App Name -->\n    <td style=\"border: none;padding-top:0px\"><p style=\"font-size:26px\">Golden Signals</b><span style=\"font-size:18px\">&nbsp;&nbsp;|&nbsp;&nbsp;${service_name}&nbsp;(${service_namespace})\n    <br></td>\n  </tr>\n  <tr>\n    <!-- Dashboard Sub-Navigation -->\n    <td style=\"border: none;padding-top:0px\">\n      <nav style=\"font-size:14px;text-align:left;\">\n          <a href=#>Databases</a>&nbsp;&nbsp;|&nbsp;\n          <a href=\"https://richgeorge.grafana.net/d/cefgd4x4bolxcb?&var-service_name=${service_name}&var-service_namespace=${service_namespace}&var-env=${env}&var-quant=${quant}\">Endpoints</a>&nbsp;&nbsp;|&nbsp;\n          Golden Signals&nbsp;&nbsp;|&nbsp;\n          <a href=#>HTTP</a>&nbsp;&nbsp;|&nbsp;\n          <a href=#>JVM</a>&nbsp;&nbsp;|&nbsp;\n          <a href=#>RPC</a>&nbsp;&nbsp;|&nbsp;\n          <a href=\"https://richgeorge.grafana.net/d/cefgdjx1733lsc?&var-service_name=${service_name}&var-service_namespace=${service_namespace}&var-env=${env}&var-quant=${quant}\">Service Graph</a>\n        </nav>\n    </td>\n    <!-- Dashboard Main-Navigation -->\n    <td style=\"border: none;padding-top:0px;text-align: right;\"><p style=\"text-align:right;\">\n        <!-- Home -->\n        <a href=\"https://richgeorge.grafana.net/d/eefxjyho1w4jkb\"><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-home-inactive-v2.svg style=\"height:29px;\"></a>\n        <!-- SLOs -->\n        <a href=#><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-slos-inactive-v2.svg style=\"height:29px;\"></a>\n        <!-- Apps -->\n        <a href=\"https://richgeorge.grafana.net/d/beffsrurmj4lcd\"><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-apps-active-v2.svg style=\"height:29px;\"></a>\n        <!-- RUM -->\n        <a href=#><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-infra-inactive-v2.svg style=\"height:29px;\"></a>\n        <!-- Infra -->\n        <a href=#><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-tools-inactive-v2.svg style=\"height:29px;\"></a>\n        <!-- Tools -->\n        <a href=#><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-misc-inactive-v2.svg style=\"height:29px;\"></a>\n        <!-- Misc -->\n        <a href=#><img src=https://raw.githubusercontent.com/pix3lrich/grafana-image-repo/31477e5f214a12e4c052751a6b49d22ef01ae91c/navigation/navbutton-help-v2.svg style=\"height:29px;\"></a>\n    </td>\n  </tr>\n</table>\n<hr>"
   }
  },
  {
   "title": "Latency, p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"$component\"}[$__rate_interval])))",
     "legendFormat": "http_request_duration_seconds_bucket, p95"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\",path!~\"/_app.*\"}[$__rate_interval]))",
     "legendFormat": "http_requests_total"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\",status!~\"(2..|0)\"}[$__rate_interval])) / sum(rate(http_requests_total{job=\"$component\"}[$__rate_interval]))",
     "legendFormat": "http_requests_total, status=3xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\",status!~\"(2..|0)\"}[$__rate_interval])) / sum(rate(http_requests_total{job=\"$component\"}[$__rate_interval]))",
     "legendFormat": "http_requests_total, status=4xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\",status!~\"(2..|0)\"}[$__rate_interval])) / sum(rate(http_requests_total{job=\"$component\"}[$__rate_interval]))",
     "legendFormat": "http_requests_total, status=5xx"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\", status!~\"(2..|0)\"}[$__rate_interval])) / sum(rate(http_requests_total{job=\"$component\"}[$__rate_interval]))",
     "legendFormat": "buffer_filled_percent"
    }
   ]
  }
 ]
}